version: '3'
services:
  app:
    build: .
    depends_on:
    - postgres
    ports:
    - "8000:8000"
  postgres:
    image: 'postgres'
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mypassword
      
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - 5432:5432
volumes:
  db-data: